backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  squash_merges: true
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: 'post'
    label: 'Post'
    folder: 'content/en/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: "Featured Image", name: "featuredimage", widget: image, required: false }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "about"
    label: "About"
    files:
      - label: "About Page"
        name: "about"
        file: "content/en/about/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: "Featured Image", name: "featured_image", widget: image, required: false }
          - { label: "Content", name: "body", widget: "markdown" }





